codecov:
  ci:
    - !appveyor

ignore:
  - "jest"
  - "scripts/e2e"

fixes:
  - "dist/neo-one::"

comment:
  layout: "reach, diff, flags, files"

coverage:
  status:
    project:
      default:
        threshold: 0.30
