codecov:
  ci:
    - '!appveyor'

ignore:
  - 'jest'
  - 'scripts'
  - '**/__e2e__/**'
  - '**/__data__/**'

fixes:
  - 'dist/neo-one::'

comment:
  layout: 'reach, diff, flags, files'

coverage:
  status:
    project:
      default:
        threshold: 0.30
