aliases:
  - &restore-yarn-cache
    keys:
      - v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - v1-yarn-{{ .Branch }}-

  - &save-yarn-cache
    paths:
      - node_modules
      - ~/.cache/yarn
    key: v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &filter-only-master
    branches:
      only:
        - master

  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

  - &yarn
    |
      yarn install --non-interactive --cache-folder ~/.cache/yarn --frozen-lockfile

  - &test
    working_directory: ~/neo-one
    steps:
      - checkout
      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache
      - run:
          name: Build
          command: yarn build
      - run:
          name: Prettier
          command: yarn nit
      - run:
          name: Typescript
          command: yarn tsc
      - run:
          name: Lint
          command: yarn lint          
      - run:
          name: Test
          command: yarn test-ci
      - run:
          name: E2E
          command: yarn e2e-ci

node8.9: &node8.9
  docker:
    - image: circleci/node:8.9

node9: &node9
  docker:
    - image: circleci/node:9

node10: &node10
  docker:
    - image: circleci/node:10

version: 2
jobs:
  test8.9:
    <<: *node8.9
    <<: *test

  test9:
    <<: *node9
    <<: *test

  test10:
    <<: *node10
    <<: *test     

  deploy-website:
    <<: *node8.9
    working_directory: ~/neo-one/website
    steps:
      - checkout:
          path: ~/neo-one
      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache
      - run:
          name: Install Dependencies
          command: sudo apt install rsync
      - run:
          name: Deploy Website
          command: |
            git config --global user.email "dicarlo2@users.noreply.github.com"
            git config --global user.name "Alex DiCarlo"
            echo "machine github.com login dicarlo2 password $GITHUB_TOKEN" > ~/.netrc
            echo "Deploying website..."
            GIT_USER=dicarlo2 yarn run publish-gh-pages

workflows:
  version: 2
  website:
    jobs:
      - deploy-website:
          filters: *filter-only-master
  test:
    jobs:
      - test8.9:
          filters: *filter-ignore-gh-pages
      - test9:
          filters: *filter-ignore-gh-pages
      - test10:
          filters: *filter-ignore-gh-pages          
